spring:
  datasource:
    url: jdbc:mysql://localhost/jwt
    username: root
    password: Optimus@2399
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
